"""
read_markdown/markdown_loader.py
================================

THE READ SIDE OF THE MARKDOWN PIPELINE
--------------------------------------

WHAT THIS MODULE AFFECTS:
    Reads  read_markdown/app_blueprint.md    ->  config/agent.json    (name, default_model, skills,
                                                                       role, user, job, composed system_prompt)
    Reads  read_markdown/chatbot_prompt.md   ->  config/chat_bot.json (same shape as agent.json;
                                                                       built alongside it so the chat
                                                                       path can be switched later)
    Reads  write_markdown/tools.md           ->  config/tools.json    (the tools -> GET /api/tools)
    Writes (only if a blueprint is missing) the default .md templates above
    Affects POST /api/chat (the agent's identity) and GET /api/tools (the toolbox).

It is written as a CLASS (MarkdownLoader) so the same parsing logic can serve
both blueprints: each blueprint gets its own MarkdownLoader instance with its
own file paths, default template and output files.

Why a markdown file?
    A markdown file is easy for a human to read and edit: headings and bullet
    points are self-documenting, and git diffs are clean. The JSON files are
    just the machine-readable output of that file.

    models.json is deliberately NOT produced here -- the model list is dynamic
    (it changes whenever Ollama / LM Studio models change) and is owned by
    write_markdown/app_config.py (AppConfig), which scans the LLMs at startup.

    skills.json is also NOT produced here anymore -- it is generated from the
    SKILL_REGISTRY in app/tools/tools.py by AppConfig (the skills catalog /
    test point), not from the blueprint.

When does this run?
    server.py calls load_all() on startup (inside a FastAPI lifespan event),
    so any edit to either blueprint takes effect on the next server restart.
    You can also run this file directly:  python read_markdown/markdown_loader.py

If a blueprint is missing, MarkdownLoader.ensure() recreates it from the
default template embedded below, then parsing proceeds normally.
"""

import json
import re
import sys
from pathlib import Path

# --------------------------------------------------------------------------
# FILE PATHS
# --------------------------------------------------------------------------
# This module lives in read_markdown/. The JSON outputs stay in config/.
BACKEND_DIR = Path(__file__).resolve().parent.parent
CONFIG_DIR = BACKEND_DIR / "config"
BLUEPRINT_FILE = Path(__file__).resolve().parent / "app_blueprint.md"  # agent source
AGENT_FILE = CONFIG_DIR / "agent.json"            # generated output
CHATBOT_BLUEPRINT_FILE = Path(__file__).resolve().parent / "chatbot_prompt.md"  # chat_bot source
CHATBOT_FILE = CONFIG_DIR / "chat_bot.json"       # generated output
TOOLS_FILE = CONFIG_DIR / "tools.json"            # generated output

# write_markdown/ holds the tools blueprint. tools.md is auto-generated by
# write_markdown/app_config.py (from app/tools/tools.py) BEFORE this loader runs.
TOOLS_DIR = BACKEND_DIR / "write_markdown"
TOOLS_BLUEPRINT_FILE = TOOLS_DIR / "tools.md"     # tools list source (auto-generated)


# --------------------------------------------------------------------------
# DEFAULT BLUEPRINTS (the templates)
# --------------------------------------------------------------------------
# These exact texts are written when a blueprint does not exist. They are also
# the format spec: human users copy this structure to add new skills or tools.
# Keep them in sync with the on-disk .md files.

DEFAULT_BLUEPRINT = """\
# AI Agent Studio — Application Blueprint

## MAP — who uses this file

This single markdown file is the **source of truth** for the agent. At every
server start it is read and turned into `config/agent.json`, which builds the
agent served by `POST /api/chat`.

| Module | Function | Effect |
|---|---|---|
| `read_markdown/markdown_loader.py` | `MarkdownLoader.build_agent()` | READS this file → writes `config/agent.json` |
| `app/agents/chat_bot_agent.py` | `build_agent()` | READS `config/agent.json` → `Agent(profile, tools, LLMClient)` |
| `server.py` | `lifespan` → `load_all()` | triggers regeneration at every startup |
| `write_markdown/app_config.py` | `AppConfig` | does NOT read this file (models/tools come from `SKILL_REGISTRY`) |

- **JSON written:** `config/agent.json` → `{name, default_model, skills, role, user, job, system_prompt}`
- **Affects:** `POST /api/chat` (agent identity), `GET /api/tools` (skills selection)
- **Flow:** edit this file → restart server → `lifespan` → `load_all()` → `config/agent.json` → `POST /api/chat`

If this file is ever deleted, `read_markdown/markdown_loader.py` recreates it
from its default template on the next server start.

Sections below:

- `## agent`  — the agent's name, default model and skills (a comma-separated
  list; each id selects a registered tool in `app/tools/tools.py`'s SKILL_REGISTRY)
- `## role`   — who the agent is (free text)
- `## user`   — knowledge of the user (free text)
- `## job`    — what the agent does (free text)

Everything after a `##` heading until the next `##` heading is used verbatim.

---

## agent

Everything the chatbot needs at the top level.

- name: AI Agent Development Assistant
- default_model: gemma4:e2b
- skills: get_current_date

## role

You are an **AI Agent Development Assistant**.

Your primary purpose is to help the user:

* Learn how AI agents work.
* Build AI agents with Python.
* Understand agent architecture.
* Create reusable AI-agent components.
* Experiment with different approaches.
* Understand what works, what does not work, and why.
* Gradually move from simple examples to more advanced systems.

You are both a **software developer** and a **teacher**.

## user

**Name:** Jesus

**Current knowledge:**

* Knows some Python.
* Is still becoming comfortable with Python.
* Is learning AI agents.
* Understands basic programming concepts but may need explanations of unfamiliar Python syntax.

**Goal:**

Jesus wants to create **off-the-shelf AI-agent components** that can be reused
to build different AI agents. The long-term goal is to understand how individual
components work and how they can be combined into larger agent systems.

## job

Teach like a patient software-development instructor.

When explaining something:

1. Start with the simple idea.
2. Explain why it exists.
3. Show a small example.
4. Explain the important parts of the example.
5. Show how it can be modified.
6. Explain how it fits into an AI-agent system.

Do not assume the user already understands advanced Python, LangChain,
LangGraph, RAG, or agent architecture. When introducing a new concept, explain
unfamiliar terminology.

Keep examples small, copy-pasteable, and easy to modify. Write simple code over
clever code. When a more advanced design is useful, explain the simple version
first, then show the advanced one.
"""

DEFAULT_CHATBOT_BLUEPRINT = """\
# AI Agent Studio — Chat Bot Prompt

This file feeds `config/chat_bot.json` (same shape as `config/agent.json`).
Fill in the sections below; empty sections are simply skipped by the loader.

## agent

- name: Agent
- default_model: gemma4:e2b
- skills: get_current_date, tell_me_the_date_and_time, create_folder, create_file, setup_venv, read_file, write_file, read_pdf

## role

Describe who the agent is.

## user

Describe who it talks to.

## job

Describe what it does.
"""

DEFAULT_TOOLS_BLUEPRINT = """\
# AI Agent Studio — Tools (auto-generated)

> AUTO-GENERATED by `write_markdown/app_config.py` from the `SKILL_REGISTRY`
> in `app/tools/tools.py` — do not hand-edit; restart to regenerate.

If this file is ever deleted, it is recreated from this template on the next
server start, then rewritten from the registry by `AppConfig.refresh_all()`.

## tools

Each tool is a `### <id>` block.

### get_current_date
- name: Get Current Date
- icon: 🔧
- enabled: true
- description: Return the real current date as a formatted string.
"""


class MarkdownLoader:
    """Load one markdown blueprint and regenerate its JSON output file(s).

    A single instance owns ONE blueprint and the output files it produces.
    Three instances are used at module level (see below): one for the agent
    blueprint (agent.json), one for the chatbot prompt (chat_bot.json) and
    one for the tools blueprint (tools.json).
    """

    def __init__(self, blueprint_path, default_blueprint, output_paths=None):
        """Store the blueprint location, its fallback template and its outputs.

        Args:
            blueprint_path:     path to the source markdown file.
            default_blueprint:  template text written if the markdown is missing.
            output_paths:       dict mapping kind ('agent'/'tools')
                                to the output JSON file that kind is written to.
        """
        self.blueprint_path = Path(blueprint_path)
        self.default_blueprint = default_blueprint
        self.output_paths = output_paths or {}

    # ------------------------------------------------------------------
    # PARSING HELPERS (pure functions -> instance methods)
    # ------------------------------------------------------------------

    def _parse_key_value(self, text: str) -> dict:
        """Turn a block of '- key: value' bullet lines into a dictionary.

        Example input:
            - name: Save
            - icon: 💾
            - enabled: true

        Example output:
            {"name": "Save", "icon": "💾", "enabled": true}
        """
        data = {}
        for line in text.splitlines():
            # Match "- key: value" where key is letters/digits/underscore.
            match = re.match(r"^\s*-\s*([A-Za-z0-9_]+)\s*:\s*(.*)$", line)
            if match:
                value = match.group(2).strip()
                # Coerce "true"/"false" strings to real booleans so the frontend
                # gets JSON booleans instead of the strings "true"/"false".
                if value.lower() == "true":
                    value = True
                elif value.lower() == "false":
                    value = False
                data[match.group(1).strip()] = value
        return data

    def _parse_item_blocks(self, text: str) -> list:
        """Parse a '### <id>' block section (used for skills and tools).

        Each '### <id>' heading starts a new item; the '- key: value' lines
        under it become that item's fields, and the heading text becomes 'id'.

        Example input:
            ### save
            - name: Save
            - icon: 💾

        Example output:
            [{"id": "save", "name": "Save", "icon": "💾"}]
        """
        items = []
        current_id = None
        buffer = []
        for line in text.splitlines(keepends=True):
            # A level-3 heading like "### save" starts a new item.
            match = re.match(r"^\s*#{3,}\s+(.+?)\s*$", line)
            if match:
                if current_id is not None:  # flush the previous item
                    items.append({"id": current_id, **self._parse_key_value("".join(buffer))})
                current_id, buffer = match.group(1).strip(), []
            else:
                buffer.append(line)
        if current_id is not None:  # flush the last item
            items.append({"id": current_id, **self._parse_key_value("".join(buffer))})
        return items

    def _split_sections(self, text: str) -> dict:
        """Split the markdown into top-level '## <name>' sections.

        Everything after a '## name' heading (until the next '## name') is
        stored under that lower-cased name. Level-3 '###' headings do NOT
        split sections (they belong to the section that contains them).
        """
        sections = {}
        current = None
        buffer = []
        for line in text.splitlines(keepends=True):
            # Match exactly two hashes + space, so '### ' (items) is NOT a section.
            match = re.match(r"^\s*##\s+(.+?)\s*$", line)
            if match:
                if current is not None:  # flush the previous section
                    sections[current] = "".join(buffer)
                current, buffer = match.group(1).strip().lower(), []
            elif current is not None:
                buffer.append(line)
        if current is not None:  # flush the last section
            sections[current] = "".join(buffer)
        return sections

    def _clean_body(self, text: str) -> str:
        """Trim blank lines and '---' separators from the edges of a section body."""
        lines = text.splitlines()
        # Drop empty / separator lines from the top...
        while lines and (not lines[0].strip() or lines[0].strip() in ("---", "***")):
            lines.pop(0)
        # ...and from the bottom.
        while lines and (not lines[-1].strip() or lines[-1].strip() in ("---", "***")):
            lines.pop()
        return "\n".join(lines).strip("\n")

    # ------------------------------------------------------------------
    # FILE HELPERS
    # ------------------------------------------------------------------

    def ensure(self) -> Path:
        """Create the blueprint from its default template if it is missing.

        Satisfies the "if no markdown exists, make one" requirement: the app
        never crashes on a missing blueprint, it just seeds a default one.
        Returns the blueprint file path.
        """
        if not self.blueprint_path.exists():
            self.blueprint_path.parent.mkdir(parents=True, exist_ok=True)
            self.blueprint_path.write_text(self.default_blueprint, encoding="utf-8")
            print(f"[markdown_loader] created default blueprint at {self.blueprint_path}")
        return self.blueprint_path

    def write_json(self, path: Path, data: dict) -> None:
        """Write a dict to a JSON file (pretty-printed, UTF-8)."""
        path.parent.mkdir(parents=True, exist_ok=True)
        path.write_text(
            json.dumps(data, indent=2, ensure_ascii=False) + "\n",
            encoding="utf-8",
        )

    # ------------------------------------------------------------------
    # SECTION BUILDERS (markdown sections -> JSON-ready structures)
    # ------------------------------------------------------------------

    def build_agent(self, sections: dict) -> dict:
        """Build the agent.json content from the 'agent' section + 'role'/'user'/'job'.

        The three free-text sections describe the agent (role), who it talks to
        (user) and what it does (job). Each is stored raw so the JSON is
        transparent, AND they are composed into the 'system_prompt' that the
        LLM actually receives.
        """
        fields = self._parse_key_value(sections.get("agent", ""))
        # The 'skills' value is a comma-separated list -> split into a real list.
        skills = [s.strip() for s in fields.get("skills", "").split(",") if s.strip()]
        role = self._clean_body(sections.get("role", ""))
        user = self._clean_body(sections.get("user", ""))
        job = self._clean_body(sections.get("job", ""))
        return {
            "name": fields.get("name", "Agent"),
            "default_model": fields.get("default_model", ""),
            "skills": skills,
            "role": role,
            "user": user,
            "job": job,
            "system_prompt": self._compose_system_prompt(role, user, job),
        }

    @staticmethod
    def _compose_system_prompt(role: str, user: str, job: str) -> str:
        """Assemble the final system prompt from the role/user/job sections.

        Each present section is prefixed with a header line so the LLM can tell
        WHO it is, WHO it talks to, and WHAT it should do. Empty sections are
        simply skipped.
        """
        parts = []
        if role:
            parts.append(f"ROLE\n{role}")
        if user:
            parts.append(f"ABOUT THE USER\n{user}")
        if job:
            parts.append(f"JOB DESCRIPTION\n{job}")
        return "\n\n".join(parts)

    def build_tools(self, sections: dict) -> list:
        """Build the tools list from the 'tools' section ('### <id>' blocks)."""
        return self._parse_item_blocks(sections.get("tools", ""))

    # ------------------------------------------------------------------
    # MAIN ENTRY POINT
    # ------------------------------------------------------------------

    def load(self, kinds=None) -> dict:
        """Read the blueprint and regenerate the requested JSON output(s).

        Args:
            kinds: list of which configs to build + write, e.g. ["agent", "skills"].
                   Defaults to every kind this instance has an output for.

        Returns:
            dict mapping each requested kind to its parsed (JSON-ready) value.
        """
        # Default: load every kind this instance is configured to output.
        if kinds is None:
            kinds = list(self.output_paths.keys())

        self.ensure()  # 1. create the markdown if it's missing

        # 2. Read the whole blueprint and split it into its '## ' sections.
        sections = self._split_sections(self.blueprint_path.read_text(encoding="utf-8"))

        # 3. Build each requested kind and write it to its output file.
        result = {}
        for kind in kinds:
            if kind == "agent":
                data = self.build_agent(sections)
            elif kind == "chat_bot":
                data = self.build_agent(sections)
            elif kind == "tools":
                data = {"tools": self.build_tools(sections)}
            else:
                raise ValueError(f"unknown config kind: {kind!r}")

            result[kind] = data
            if kind in self.output_paths:  # persist (some kinds may not map to a file)
                self.write_json(self.output_paths[kind], data)
                print(f"[markdown_loader] regenerated {self.output_paths[kind].name} from {self.blueprint_path.name}")

        return result


# --------------------------------------------------------------------------
# MODULE-LEVEL INSTANCES + CONVENIENCE API (kept for server.py compatibility)
# --------------------------------------------------------------------------

# Loader for the agent blueprint -> agent.json.
# (skills.json is NOT built here - AppConfig generates it from tools.py.)
AGENT_LOADER = MarkdownLoader(
    blueprint_path=BLUEPRINT_FILE,
    default_blueprint=DEFAULT_BLUEPRINT,
    output_paths={"agent": AGENT_FILE},
)

# Loader for the chatbot prompt blueprint -> chat_bot.json. Same agent builder
# as AGENT_LOADER (identical JSON shape), but fed from its own markdown file.
CHATBOT_LOADER = MarkdownLoader(
    blueprint_path=CHATBOT_BLUEPRINT_FILE,
    default_blueprint=DEFAULT_CHATBOT_BLUEPRINT,
    output_paths={"chat_bot": CHATBOT_FILE},
)

# Loader for the UI tool-button blueprint -> tools.json.
TOOLS_LOADER = MarkdownLoader(
    blueprint_path=TOOLS_BLUEPRINT_FILE,
    default_blueprint=DEFAULT_TOOLS_BLUEPRINT,
    output_paths={"tools": TOOLS_FILE},
)


def load_all() -> dict:
    """Regenerate every JSON config from both blueprints.

    Steps:
        1. AGENT_LOADER.load(["agent"])      -> agent.json
        2. CHATBOT_LOADER.load(["chat_bot"]) -> chat_bot.json
        3. TOOLS_LOADER.load(["tools"])      -> tools.json
        4. return everything (also useful for debugging / tests)

    Call this from server.py's startup event so config is always fresh.
    (models.json + skills.json are generated by AppConfig, not here.)
    """
    result = {}
    result.update(AGENT_LOADER.load(kinds=["agent"]))
    result.update(CHATBOT_LOADER.load(kinds=["chat_bot"]))
    result.update(TOOLS_LOADER.load(kinds=["tools"]))
    return result


# --------------------------------------------------------------------------
# STANDALONE RUN
# --------------------------------------------------------------------------
if __name__ == "__main__":
    # Running `python read_markdown/markdown_loader.py` regenerates the JSON files
    # and prints what was parsed (handy for eyeballing the result).
    # Force UTF-8 output so emoji (e.g. tool icons like 💾) survive the print
    # on Windows consoles, which default to the cp1252 codepage.
    sys.stdout.reconfigure(encoding="utf-8")
    result = load_all()
    print(json.dumps(result, indent=2, ensure_ascii=False))
