"""
read_markdown/markdown_loader.py
================================

THE READ SIDE OF THE MARKDOWN PIPELINE
--------------------------------------

WHAT THIS MODULE AFFECTS:
    Reads  read_markdown/chat_bot_agent.md  ->  config/chat_bot.json    (identity, role, personality,
                                                                         boundaries, skills, etc.)
    Reads  read_markdown/skills/*.md        ->  config/skills.json      (detailed skill documentation)
    Reads  write_markdown/tools.md          ->  config/tools.json       (the tools -> GET /api/tools)
    Affects POST /api/chat (the agent's identity) and GET /api/tools (the toolbox).

If a blueprint is missing, the loader raises FileNotFoundError. The server
catches this and falls back to a minimal chatbot (no tools, basic prompt).
No default templates are embedded — the markdown files are the source of truth.

When does this run?
    server.py calls load_all() on startup (inside a FastAPI lifespan event),
    so any edit to a blueprint takes effect on the next server restart.
    You can also run this file directly:  python read_markdown/markdown_loader.py
"""

import json
import re
import sys
from pathlib import Path

# --------------------------------------------------------------------------
# FILE PATHS
# --------------------------------------------------------------------------
# This module lives in read_markdown/. The JSON outputs stay in config/.
BACKEND_DIR = Path(__file__).resolve().parent.parent
CONFIG_DIR = BACKEND_DIR / "config"

# Agent definition source -> chat_bot.json
AGENT_DEF_FILE = Path(__file__).resolve().parent / "chat_bot_agent.md"
CHATBOT_FILE = CONFIG_DIR / "chat_bot.json"

# Basic chatbot definition -> chat_bot_basic.json
BASIC_DEF_FILE = Path(__file__).resolve().parent / "chat_bot_basic.md"
BASIC_FILE = CONFIG_DIR / "chat_bot_basic.json"

# Skills folder -> skills.json
SKILLS_DIR = Path(__file__).resolve().parent / "skills"
SKILLS_FILE = CONFIG_DIR / "skills.json"

# Tools blueprint -> tools.json (auto-generated by write_markdown/app_config.py)
TOOLS_DIR = BACKEND_DIR / "write_markdown"
TOOLS_BLUEPRINT_FILE = TOOLS_DIR / "tools.md"
TOOLS_FILE = CONFIG_DIR / "tools.json"


# Sections that get structured handling in build_agent(). Any other '## section'
# found in an agent blueprint passes through verbatim into the agent JSON (and
# later into the system prompt via AgentProfile.extras) - no code changes needed
# to introduce new prompt sections.
HANDLED_SECTIONS = {
    "identity", "skills", "role", "purpose", "personality",
    "communication", "boundaries", "principles", "decision_style", "priorities",
}


class MarkdownLoader:
    """Load one markdown blueprint and regenerate its JSON output file(s).

    A single instance owns ONE blueprint and the output files it produces.
    Two instances are used at module level (see below): one for the agent
    definition (chat_bot.json) and one for the tools blueprint (tools.json).
    """

    def __init__(self, blueprint_path, output_paths=None):
        """Store the blueprint location and its output files.

        Args:
            blueprint_path:     path to the source markdown file.
            output_paths:       dict mapping kind ('agent'/'tools')
                                to the output JSON file that kind is written to.
        """
        self.blueprint_path = Path(blueprint_path)
        self.output_paths = output_paths or {}

    # ------------------------------------------------------------------
    # PARSING HELPERS
    # ------------------------------------------------------------------

    def _parse_key_value(self, text: str) -> dict:
        """Turn a block of '- key: value' bullet lines into a dictionary."""
        data = {}
        for line in text.splitlines():
            match = re.match(r"^\s*-\s*([A-Za-z0-9_]+)\s*:\s*(.*)$", line)
            if match:
                value = match.group(2).strip()
                if value.lower() == "true":
                    value = True
                elif value.lower() == "false":
                    value = False
                data[match.group(1).strip()] = value
        return data

    def _parse_item_blocks(self, text: str) -> list:
        """Parse a '### <id>' block section (used for tools)."""
        items = []
        current_id = None
        buffer = []
        for line in text.splitlines(keepends=True):
            match = re.match(r"^\s*#{3,}\s+(.+?)\s*$", line)
            if match:
                if current_id is not None:
                    items.append({"id": current_id, **self._parse_key_value("".join(buffer))})
                current_id, buffer = match.group(1).strip(), []
            else:
                buffer.append(line)
        if current_id is not None:
            items.append({"id": current_id, **self._parse_key_value("".join(buffer))})
        return items

    def _parse_skills_table(self, text: str) -> list:
        """Parse a markdown table from the ## skills section."""
        items = []
        for line in text.splitlines():
            line = line.strip()
            if not line or line.startswith("|--") or line.startswith("| Skill"):
                continue
            match = re.match(r"^\|\s*(.+?)\s*\|\s*(.+?)\s*\|\s*(.+?)\s*\|$", line)
            if match:
                skill_id = match.group(1).strip()
                description = match.group(2).strip()
                docs = match.group(3).strip()
                link_match = re.search(r"\[.*?\]\((.+?)\)", docs)
                docs_path = link_match.group(1) if link_match else ""
                items.append({
                    "id": skill_id,
                    "description": description,
                    "docs": docs_path,
                })
        return items

    def _split_sections(self, text: str) -> dict:
        """Split the markdown into top-level '## <name>' sections."""
        sections = {}
        current = None
        buffer = []
        for line in text.splitlines(keepends=True):
            match = re.match(r"^\s*##\s+(.+?)\s*$", line)
            if match:
                if current is not None:
                    sections[current] = "".join(buffer)
                current, buffer = match.group(1).strip().lower(), []
            elif current is not None:
                buffer.append(line)
        if current is not None:
            sections[current] = "".join(buffer)
        return sections

    def _clean_body(self, text: str) -> str:
        """Trim blank lines and '---' separators from the edges of a section body."""
        lines = text.splitlines()
        while lines and (not lines[0].strip() or lines[0].strip() in ("---", "***")):
            lines.pop(0)
        while lines and (not lines[-1].strip() or lines[-1].strip() in ("---", "***")):
            lines.pop()
        return "\n".join(lines).strip("\n")

    # ------------------------------------------------------------------
    # FILE HELPERS
    # ------------------------------------------------------------------

    def ensure(self) -> Path:
        """Raise FileNotFoundError if the blueprint file is missing."""
        if not self.blueprint_path.exists():
            raise FileNotFoundError(
                f"Blueprint not found: {self.blueprint_path}\n"
                f"Create it or restore from git."
            )
        return self.blueprint_path

    def write_json(self, path: Path, data: dict) -> None:
        """Write a dict to a JSON file (pretty-printed, UTF-8)."""
        path.parent.mkdir(parents=True, exist_ok=True)
        path.write_text(
            json.dumps(data, indent=2, ensure_ascii=False) + "\n",
            encoding="utf-8",
        )

    # ------------------------------------------------------------------
    # SECTION BUILDERS (markdown sections -> JSON-ready structures)
    # ------------------------------------------------------------------

    def build_agent(self, sections: dict) -> dict:
        """Build chat_bot.json content from the agent definition markdown sections."""
        identity = self._parse_key_value(sections.get("identity", ""))
        skills_table = self._parse_skills_table(sections.get("skills", ""))
        skill_ids = [s["id"] for s in skills_table]
        role = self._clean_body(sections.get("role", ""))
        purpose = self._clean_body(sections.get("purpose", ""))
        personality = self._clean_body(sections.get("personality", ""))
        communication = self._clean_body(sections.get("communication", ""))
        boundaries = self._clean_body(sections.get("boundaries", ""))
        principles = self._clean_body(sections.get("principles", ""))
        decision_style = self._clean_body(sections.get("decision_style", ""))
        priorities = self._clean_body(sections.get("priorities", ""))

        data = {
            "name": identity.get("name", "Agent"),
            "default_model": identity.get("default_model", ""),
            "type": identity.get("type", ""),
            "skills": skill_ids,
            "skills_table": skills_table,
            "role": role,
            "purpose": purpose,
            "personality": personality,
            "communication": communication,
            "boundaries": boundaries,
            "principles": principles,
            "decision_style": decision_style,
            "priorities": priorities,
            "system_prompt": "",
        }
        # GENERIC PASSTHROUGH: sections without structured handling (user,
        # greeting, project_notes, ...) are copied verbatim so they can reach
        # the system prompt. Never overwrites a structured key.
        for section_name, body in sections.items():
            if section_name not in HANDLED_SECTIONS and section_name not in data:
                data[section_name] = self._clean_body(body)
        return data

    def build_tools(self, sections: dict) -> list:
        """Build the tools list from the 'tools' section ('### <id>' blocks)."""
        return self._parse_item_blocks(sections.get("tools", ""))

    # ------------------------------------------------------------------
    # MAIN ENTRY POINT
    # ------------------------------------------------------------------

    def load(self, kinds=None) -> dict:
        """Read the blueprint and regenerate the requested JSON output(s).

        Raises FileNotFoundError if the blueprint file is missing.
        """
        if kinds is None:
            kinds = list(self.output_paths.keys())

        self.ensure()

        sections = self._split_sections(self.blueprint_path.read_text(encoding="utf-8"))

        result = {}
        for kind in kinds:
            if kind == "agent" or kind == "chat_bot":
                data = self.build_agent(sections)
            elif kind == "tools":
                data = {"tools": self.build_tools(sections)}
            else:
                raise ValueError(f"unknown config kind: {kind!r}")

            result[kind] = data
            if kind in self.output_paths:
                self.write_json(self.output_paths[kind], data)
                print(f"[markdown_loader] regenerated {self.output_paths[kind].name} from {self.blueprint_path.name}")

        return result


# --------------------------------------------------------------------------
# SKILLS FOLDER PARSER
# --------------------------------------------------------------------------

def _parse_skill_file(filepath: Path) -> dict:
    """Parse a single skill markdown file into a dict."""
    text = filepath.read_text(encoding="utf-8")
    sections = {}
    current = None
    buffer = []
    for line in text.splitlines(keepends=True):
        match = re.match(r"^##\s+(.+?)\s*$", line)
        if match:
            if current is not None:
                sections[current] = "".join(buffer).strip()
            current = match.group(1).strip().lower().replace(" ", "_")
            buffer = []
        elif current is not None:
            buffer.append(line)
    if current is not None:
        sections[current] = "".join(buffer).strip()

    title_match = re.match(r"^#\s+Skill:\s+(.+?)\s*$", text)
    name = title_match.group(1) if title_match else filepath.stem

    parameters = []
    param_text = sections.get("parameters", "")
    for line in param_text.splitlines():
        line = line.strip()
        if line.startswith("-"):
            param_match = re.match(r"^-\s*`(\w+)`\s*\((.+?)\):\s*(.*)$", line)
            if param_match:
                param_name = param_match.group(1)
                param_meta = param_match.group(2)
                param_desc = param_match.group(3)
                parts = [p.strip() for p in param_meta.split(",")]
                param_type = parts[0] if parts else "string"
                required = parts[1].lower() == "required" if len(parts) > 1 else True
                parameters.append({
                    "name": param_name,
                    "type": param_type,
                    "required": required,
                    "description": param_desc,
                })

    related = []
    related_text = sections.get("related_skills", "")
    for line in related_text.splitlines():
        line = line.strip()
        if line.startswith("-"):
            rel_match = re.match(r"^-\s*(\w+)", line)
            if rel_match:
                related.append(rel_match.group(1))

    return {
        "id": filepath.stem,
        "name": name,
        "function": filepath.stem,
        "purpose": sections.get("purpose", ""),
        "when_to_use": [l.strip("- ") for l in sections.get("when_to_use", "").splitlines() if l.strip().startswith("-")],
        "parameters": parameters,
        "example": sections.get("example", ""),
        "returns": sections.get("returns", ""),
        "requirements": sections.get("requirements", ""),
        "related_skills": related,
    }


def build_skills_from_folder() -> dict:
    """Read all skill .md files from read_markdown/skills/ and write config/skills.json."""
    skills = []
    if SKILLS_DIR.exists():
        for filepath in sorted(SKILLS_DIR.glob("*.md")):
            if filepath.name.startswith("_"):
                continue
            skill = _parse_skill_file(filepath)
            skills.append(skill)

    data = {"skills": skills}
    CONFIG_DIR.mkdir(parents=True, exist_ok=True)
    SKILLS_FILE.write_text(
        json.dumps(data, indent=2, ensure_ascii=False) + "\n",
        encoding="utf-8",
    )
    print(f"[markdown_loader] regenerated {SKILLS_FILE.name} from {SKILLS_DIR.name}/")
    return data


# --------------------------------------------------------------------------
# MODULE-LEVEL INSTANCES + CONVENIENCE API
# --------------------------------------------------------------------------

# Loader for the agent definition -> chat_bot.json
AGENT_LOADER = MarkdownLoader(
    blueprint_path=AGENT_DEF_FILE,
    output_paths={"agent": CHATBOT_FILE},
)

# Loader for the basic chatbot definition -> chat_bot_basic.json
BASIC_LOADER = MarkdownLoader(
    blueprint_path=BASIC_DEF_FILE,
    output_paths={"agent": BASIC_FILE},
)

# Loader for the UI tool-button blueprint -> tools.json
TOOLS_LOADER = MarkdownLoader(
    blueprint_path=TOOLS_BLUEPRINT_FILE,
    output_paths={"tools": TOOLS_FILE},
)


def load_all() -> dict:
    """Regenerate every JSON config from the markdown blueprints.

    Catches FileNotFoundError for agent and tools blueprints — if a file
    is missing, that config is simply not generated (the server falls back
    to a minimal chatbot). Skills are always generated if the folder exists.

    Call this from server.py's startup event so config is always fresh.
    """
    result = {}
    try:
        result.update(AGENT_LOADER.load(kinds=["agent"]))
    except FileNotFoundError as e:
        print(f"[markdown_loader] {e} - no agent available")
    try:
        result.update(BASIC_LOADER.load(kinds=["agent"]))
    except FileNotFoundError as e:
        print(f"[markdown_loader] {e} - no basic chatbot available")
    try:
        result.update(TOOLS_LOADER.load(kinds=["tools"]))
    except FileNotFoundError as e:
        print(f"[markdown_loader] {e} - no tools available")
    result.update(build_skills_from_folder())
    return result


# --------------------------------------------------------------------------
# STANDALONE RUN
# --------------------------------------------------------------------------
if __name__ == "__main__":
    sys.stdout.reconfigure(encoding="utf-8")
    result = load_all()
    print(json.dumps(result, indent=2, ensure_ascii=False))
